# Generated by Django 5.1 on 2024-08-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='birth_data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
