# Generated by Django 5.1 on 2024-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0004_alter_trainee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
